apiVersion: v1
kind: ServiceAccount
metadata:
  name: semaphore-agent-svc-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: semaphore-agent-svc-account
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: semaphore-agent-svc-account
subjects:
- kind: ServiceAccount
  name: semaphore-agent-svc-account
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: semaphore-agent-svc-account
